/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        'xs': '438px',
        'md': '800px',
        'lg2': '1160px',
      },
      colors: {
        "ellie-black": "#000000",
        "ellie-darkGrey": "#494040",
        "ellie-grey": "#5B5B5B",
        "ellie-lightGrey": '#b8b8b8',
        "ellie-white": "#ffffff",
        
        "ellie-pink": "#DF5757",
        "ellie-lightPink": "#ffefef",
        
        "ellie-yellow": "#E88E01",
      },
    },
    fontFamily: {
      primary: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', 'sans-serif'],
      code: ['source-code-pro', 'Menlo', 'Monaco', 'Consolas', 'Courier New', 'monospace'],
    }
  },
  safelist: [
    'object-left',
    'object-center',
    'object-right',
    'object-bottom',
    'col',
    'col-auto',
    'col-1',
    'col-2',
    'col-3',
    'col-4',
    'col-5',
    'col-6',
    'col-7',
    'col-8',
    'col-9',
    'col-10',
    'col-11',
    'col-12',
    'sm:col',
    'sm:col-auto',
    'sm:col-1',
    'sm:col-2',
    'sm:col-3',
    'sm:col-4',
    'sm:col-5',
    'sm:col-6',
    'sm:col-7',
    'sm:col-8',
    'sm:col-9',
    'sm:col-10',
    'sm:col-11',
    'sm:col-12',
    'md:col',
    'lg:col-auto',
    'lg:col-1',
    'lg:col-2',
    'lg:col-3',
    'lg:col-4',
    'lg:col-5',
    'lg:col-6',
    'lg:col-7',
    'lg:col-8',
    'lg:col-9',
    'lg:col-10',
    'lg:col-11',
    'lg:col-12',
  ],
  plugins: [],
}
